<a href="https://colab.research.google.com/github/vishnu-kanishk/ML-Projects-2023/blob/main/ML-Models/LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
dataset = pd.read_csv("/content/Malware dataset.csv")

In [ ]:
dataset

hash  millisecond  \
0      42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...            0   
1      42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...            1   
2      42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...            2   
3      42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...            3   
4      42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...            4   
...                                                  ...          ...   
99995  025c63d266e05d9e3bd57dd9ebd0abe904616f569fe4e2...          995   
99996  025c63d266e05d9e3bd57dd9ebd0abe904616f569fe4e2...          996   
99997  025c63d266e05d9e3bd57dd9ebd0abe904616f569fe4e2...          997   
99998  025c63d266e05d9e3bd57dd9ebd0abe904616f569fe4e2...          998   
99999  025c63d266e05d9e3bd57dd9ebd0abe904616f569fe4e2...          999   

      classification  state  usage_counter        prio  static_prio  \
0            malware      0              0  3069378560        14274   
1            malware      0              0  3069378560        14274   
2            malware      0              0  3069378560        14274   
3            malware      0              0  3069378560        14274   
4            malware      0              0  3069378560        14274   
...              ...    ...            ...         ...          ...   
99995        malware   4096              0  3070148608        13988   
99996        malware   4096              0  3070148608        13988   
99997        malware   4096              0  3070148608        13988   
99998        malware   4096              0  3070148608        13988   
99999        malware   4096              0  3070148608        13988   

       normal_prio  policy  vm_pgoff  ...  nivcsw  min_flt  maj_flt  \
0                0       0         0  ...       0        0      120   
1                0       0         0  ...       0        0      120   
2                0       0         0  ...       0        0      120   
3                0       0         0  ...       0        0      120   
4                0       0         0  ...       0        0      120   
...            ...     ...       ...  ...     ...      ...      ...   
99995            0       0         0  ...       2        1      120   
99996            0       0         0  ...       2        1      120   
99997            0       0         0  ...       2        1      120   
99998            0       0         0  ...       2        1      120   
99999            0       0         0  ...       2        1      120   

       fs_excl_counter        lock   utime  stime  gtime  cgtime  signal_nvcsw  
0                    0  3204448256  380690      4      0       0             0  
1                    0  3204448256  380690      4      0       0             0  
2                    0  3204448256  380690      4      0       0             0  
3                    0  3204448256  380690      4      0       0             0  
4                    0  3204448256  380690      4      0       0             0  
...                ...         ...     ...    ...    ...     ...           ...  
99995                0  3204448256  371979      3      0       0             0  
99996                0  3204448256  371979      3      0       0             0  
99997                0  3204448256  371979      3      0       0             0  
99998                0  3204448256  371979      3      0       0             0  
99999                0  3204448256  371979      3      0       0             0  

[100000 rows x 35 columns]

In [ ]:
dataset2 = dataset.copy()
dataset2 = dataset2.drop("classification", axis=1)
dataset2

hash  millisecond  state  \
0      42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...            0      0   
1      42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...            1      0   
2      42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...            2      0   
3      42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...            3      0   
4      42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...            4      0   
...                                                  ...          ...    ...   
99995  025c63d266e05d9e3bd57dd9ebd0abe904616f569fe4e2...          995   4096   
99996  025c63d266e05d9e3bd57dd9ebd0abe904616f569fe4e2...          996   4096   
99997  025c63d266e05d9e3bd57dd9ebd0abe904616f569fe4e2...          997   4096   
99998  025c63d266e05d9e3bd57dd9ebd0abe904616f569fe4e2...          998   4096   
99999  025c63d266e05d9e3bd57dd9ebd0abe904616f569fe4e2...          999   4096   

       usage_counter        prio  static_prio  normal_prio  policy  vm_pgoff  \
0                  0  3069378560        14274            0       0         0   
1                  0  3069378560        14274            0       0         0   
2                  0  3069378560        14274            0       0         0   
3                  0  3069378560        14274            0       0         0   
4                  0  3069378560        14274            0       0         0   
...              ...         ...          ...          ...     ...       ...   
99995              0  3070148608        13988            0       0         0   
99996              0  3070148608        13988            0       0         0   
99997              0  3070148608        13988            0       0         0   
99998              0  3070148608        13988            0       0         0   
99999              0  3070148608        13988            0       0         0   

       vm_truncate_count  ...  nivcsw  min_flt  maj_flt  fs_excl_counter  \
0                  13173  ...       0        0      120                0   
1                  13173  ...       0        0      120                0   
2                  13173  ...       0        0      120                0   
3                  13173  ...       0        0      120                0   
4                  13173  ...       0        0      120                0   
...                  ...  ...     ...      ...      ...              ...   
99995              10406  ...       2        1      120                0   
99996              10406  ...       2        1      120                0   
99997              10406  ...       2        1      120                0   
99998              10406  ...       2        1      120                0   
99999              10406  ...       2        1      120                0   

             lock   utime  stime  gtime  cgtime  signal_nvcsw  
0      3204448256  380690      4      0       0             0  
1      3204448256  380690      4      0       0             0  
2      3204448256  380690      4      0       0             0  
3      3204448256  380690      4      0       0             0  
4      3204448256  380690      4      0       0             0  
...           ...     ...    ...    ...     ...           ...  
99995  3204448256  371979      3      0       0             0  
99996  3204448256  371979      3      0       0             0  
99997  3204448256  371979      3      0       0             0  
99998  3204448256  371979      3      0       0             0  
99999  3204448256  371979      3      0       0             0  

[100000 rows x 34 columns]

In [ ]:
X = dataset2.iloc[:, 1:].values
y = dataset.iloc[:, 2].values
X
y

array(['malware', 'malware', 'malware', ..., 'malware', 'malware',
       'malware'], dtype=object)

In [ ]:
print(X)

[[   0    0    0 ...    0    0    0]
 [   1    0    0 ...    0    0    0]
 [   2    0    0 ...    0    0    0]
 ...
 [ 997 4096    0 ...    0    0    0]
 [ 998 4096    0 ...    0    0    0]
 [ 999 4096    0 ...    0    0    0]]


In [ ]:
y

array(['malware', 'malware', 'malware', ..., 'malware', 'malware',
       'malware'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
y

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
dataset.isnull().sum()

hash                 0
millisecond          0
classification       0
state                0
usage_counter        0
prio                 0
static_prio          0
normal_prio          0
policy               0
vm_pgoff             0
vm_truncate_count    0
task_size            0
cached_hole_size     0
free_area_cache      0
mm_users             0
map_count            0
hiwater_rss          0
total_vm             0
shared_vm            0
exec_vm              0
reserved_vm          0
nr_ptes              0
end_data             0
last_interval        0
nvcsw                0
nivcsw               0
min_flt              0
maj_flt              0
fs_excl_counter      0
lock                 0
utime                0
stime                0
gtime                0
cgtime               0
signal_nvcsw         0
dtype: int64

In [ ]:
X[-1]

array([       999,       4096,          0, 3070148608,      13988,
                0,          0,          0,      10406,          0,
                0,          0,        616,       3651,          0,
               40,        120,         97,         90,          0,
              120,          0,     337688,          2,          1,
              120,          0, 3204448256,     371979,          3,
                0,          0,          0])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=45)

In [ ]:
print(X_train)

[[ 417    0    0 ...    0    0    0]
 [ 837    0    0 ...    0    0    0]
 [ 858    0    0 ...    5    0    0]
 ...
 [  12    0    0 ...    0    0    0]
 [ 107 4096    0 ...    0    0    0]
 [ 558    0    0 ...    0    0    0]]


In [ ]:
y_train

array([1, 1, 0, ..., 0, 1, 0])

In [ ]:
y_test

array([1, 1, 0, ..., 0, 0, 0])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=45)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=45)

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
y_pred

array([1, 1, 0, ..., 0, 0, 0])

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
accuracy_score(y_test, y_pred)

[[13896  1147]
 [  682 14275]]


0.9390333333333334